export const STORE_USER_POSITION = 'STORE_USER_POSITION';
export const GET_GOOGLE_PLACES = 'GET_GOOGLE_PLACES';
export const EMPTY_SEARCH = 'EMPTY_SERACH';
export const GET_PLACE_LOCATION = 'GET_PLACE_LOCATION';
export const STORE_SELECTED_PLACE_NAME = 'STORE_SELECTED_PLACE_NAME';