export const CONFIRM_REQUEST = 'CONFIRM_REQUEST';
export const SUBMIT_ACTIVITY_INFOS = 'SUBMIT_ACTIVITY_INFOS';
export const FETCH_ALL_REQUEST = 'FETCH_ALL_REQUEST';
export const FETCH_ALL_MY_REQUESTS = 'FETCH_ALL_MY_REQUESTS';
export const GET_REQUEST_INFO = 'GET_REQUEST_INFO';
